spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 281477078947-05ij733d1dgask1m3vvf7pajtgq3f0b7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile